# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # secret_key_base: d38abee00a43087d76e1c8f5489957a7301b075f035978d752fcb93dbddb60cfcd448e6946b64724833baa38c42646da9b667448e8d3e73d66ac975126b5d596
  Braintree::Configuration.environment = :sandbox
  Braintree::Configuration.merchant_id = "MERCHANT_ID"
  Braintree::Configuration.public_key = "PUBLIC_KEY"
  Braintree::Configuration.private_key = "use_your_private_key"

test:
  # secret_key_base: fe75347b21767eca1cb09b7d63cc7c4bb3b20925acd382a593e24818d9d04d3c049441e3a2002aff7262794b818c7fc7abba58eb654bfba80e2a61f0be9202c6
  Braintree::Configuration.environment = :sandbox
  Braintree::Configuration.merchant_id = "MERCHANT_ID"
  Braintree::Configuration.public_key = "PUBLIC_KEY"
  Braintree::Configuration.private_key = "use_your_private_key"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  Braintree::Configuration.environment = :sandbox
  Braintree::Configuration.merchant_id = "MERCHANT_ID"
  Braintree::Configuration.public_key = "PUBLIC_KEY"
  Braintree::Configuration.private_key = "use_your_private_key"
